@startuml

title Red strike

class Worker{
    FullName
    Birthdate
    EmailAddress
    PhoneNumber
}

class Company{
    Name
}

class Address{
    AddressLine1
    AddressLine2
    PostCode
    City
    Street
    Building
    Flat
}

class Country{
    Name
}

class City{
    Name
}

class TradeUnion{
    Name
    FoundationDate
    ReadinessToStrike: ReadinessToStrikeTypes
}

class Strike{
    Theme
    DateFrom
    DateTo
}

class WorkerInTradeUnion{
    Role
}

class Employment{
    Post
}

class CompanyHasAddress{
    CompanyAddressType
}

class TradeUnionOnStrike{
    DateFrom
    DateTo
}

Worker }o-r-o{ Company : works for

(Worker, Company) .. Employment

Worker }o-d-o{ TradeUnion: takes part in

(Worker, TradeUnion) .. WorkerInTradeUnion

Company |o-r-o{ Address: has

(Company, Address) .. CompanyHasAddress

Country |o-l-o{ Address

City |o-u-o{ Address

Country ||-d-o{ City

TradeUnion }o-r-o{ Strike: takes part in

(TradeUnion, Strike) .. TradeUnionOnStrike

TradeUnionOnStrike |o-u-o{ Address: takes place in

hide methods
hide circle

@enduml